#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/upg_magazin
#    username: myuser
#    password: mysecretpassword
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
